### ISSUE TITLE
SSL, HTTP/2 support

### ISSUE THREAD

**Issue by H-Plus-Time** [maplibre/martin#17]
So Actix added SSL a while back (marginal benefit really), and recently HTTP/2; I've confirmed that both work behind nginx (or whichever other reverse proxy you care to use), though it would be nice for dev purposes to be able to run it standalone with HTTP/2, given the noticeable queueing effect incurred by HTTP/1.1 (irrespective of load on the database workers). 

I'll tinker with it over the coming weekend (should be relatively straightforward), would you mind if I submit a PR to that effect?

**Comment by stepankuzmin** [comment]
Hey @H-Plus-Time! Thanks for filling an issue for that! I'll gladly review a PR for this.

**Comment by shaunakv1** [comment]
I tried to deploy this docker image on heroku and it fails on database connection because Heroku enforces SSL connections only.  Is this a known issue? 

I see this issue in the `rust-postgres` library and unsure if that's what am running into:

https://github.com/sfackler/rust-postgres/issues/297

Do you have any recommendations on how I get around it? 

Thanks!

**Comment by stepankuzmin** [comment]
Hi @shaunakv1!

Could you please create a separate issue for this and provide steps to reproduce?

**Comment by nyurik** [comment]
Should this be closed?  We are now using the latest actix framework. I don't know the context of this issue, please close if no longer relevant.

**Comment by nyurik** [comment]
i think we already support all this
