### ISSUE TITLE
JSON/JSONB column not exposed as feature properties

### ISSUE THREAD

**Issue by mz8i** [maplibre/martin#222]
I noticed that when I have a source table that contains some data in a JSONB-type column, that data is not exposed as properties of the vector tiles features.

My current workaround was to create a text column with the serialised JSON values - but that would not have worked if I was not able to change the structure of the source table. 

I am wondering if this dropping of JSON columns should be considered a bug, or if not then what would be a suggested solution that would allow me to read the JSON values from the vector tiles, without modifying the table?

**Comment by saosebastiao** [comment]
I believe this is actually a bug in the ST_AsMVT implementation in PostGIS. When I run the queries manually, the attributes are not showing up.

**Comment by saosebastiao** [comment]
This has been bugging me a bit, as I've wanted to pass nested JSON columns into my geometry properties. I can confirm this is an issue with PostGIS, however it looks like it is by design: 

`To use this capability supply a JSONB column in the row data containing Json objects one level deep. The keys and values in the JSONB values will be encoded as feature attributes.`

https://postgis.net/docs/ST_AsMVT.html

Playing around with it, it seems as though you can supply a jsonb column, or multiple non-jsonb columns, but not both. And the object can only have attributes one level deep...no arrays or nested objects. 

I think this is a closable issue here, but maybe this should be brought up with the PostGIS team, as it would definitely be nice to have objects of arbitrary depth as feature properties.

**Comment by stepankuzmin** [comment]
Thanks for looking into this, @saosebastiao
